# Customer Satisfaction Analysis in Olist Marketplace

## Introducción

En este proyecto se realizará un Análisis Exploratorio de Datos (EDA) utilizando el dataset **Brazilian E-commerce Public Dataset by Olist** con el objetivo de comprender qué factores influyen en la satisfacción de los clientes dentro del marketplace.

A partir de la integración de diferentes tablas se analizarán pedidos, entregas, pagos, productos y reseñas para obtener información que permita explicar el comportamiento de las calificaciones otorgadas por los clientes.

## Objetivo

Analizar los principales factores asociados a la satisfacción del cliente, evaluando el impacto de los tiempos de entrega, el valor de las compras y otras variables relevantes del proceso de venta.

## Hipótesis

Se plantea que **los retrasos en la entrega tienen un mayor impacto en la satisfacción del cliente que el valor económico de la compra**, provocando una disminución en las calificaciones otorgadas cuando los pedidos son entregados fuera del plazo esperado.

Esta hipótesis será evaluada a lo largo del análisis mediante diferentes técnicas de exploración y visualización de datos.

## Data Loading

En esta sección se cargarán los distintos conjuntos de datos que conforman el marketplace Olist. Cada tabla será analizada de forma individual para comprender su estructura, identificar las variables disponibles y determinar cómo se relaciona con el resto de la información antes de iniciar el proceso de integración y análisis.

In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [173]:
customers_df = pd.read_csv('../data/raw/olist_customers_dataset.csv')
geolocation_df = pd.read_csv('../data/raw/olist_geolocation_dataset.csv')
order_items_df = pd.read_csv('../data/raw/olist_order_items_dataset.csv')
order_payments_df = pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
order_reviews_df = pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
orders_df = pd.read_csv('../data/raw/olist_orders_dataset.csv')
products_df = pd.read_csv('../data/raw/olist_products_dataset.csv')
sellers_df = pd.read_csv('../data/raw/olist_sellers_dataset.csv')
product_category_name_translation_df = pd.read_csv('../data/raw/product_category_name_translation.csv')

## Data Understanding

En esta etapa se realiza una primera exploración de cada uno de los datasets con el objetivo de comprender su estructura, identificar las variables disponibles y reconocer cómo se relacionan entre sí.

Para cada tabla se analizará su contenido, dimensiones y tipos de datos, estableciendo una base para las siguientes etapas de preparación e integración de la información.

### Customer

In [174]:
customers_df.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [175]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [176]:
customers_df.shape

(99441, 5)

### Geolocalitation

In [177]:
geolocation_df.head(5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [178]:
geolocation_df.shape

(1000163, 5)

In [179]:
geolocation_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

### Order Items

In [180]:
order_items_df.head(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [181]:
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [182]:
order_items_df.shape

(112650, 7)

### Order Payments

In [183]:
order_payments_df.head(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [184]:
order_payments_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [185]:
order_payments_df.shape

(103886, 5)

### Order Reviews

In [186]:
order_reviews_df.head(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [187]:
order_reviews_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  str
 1   order_id                 100000 non-null  str
 2   review_score             100000 non-null  int64
 3   review_comment_title     11715 non-null   str
 4   review_comment_message   41753 non-null   str
 5   review_creation_date     100000 non-null  str
 6   review_answer_timestamp  100000 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [188]:
order_reviews_df.shape

(100000, 7)

### Ordenes

In [189]:
orders_df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [190]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [191]:
orders_df.shape

(99441, 8)

### Products

In [192]:
products_df.head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [193]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [194]:
products_df.shape

(32951, 9)

### Sellers

In [195]:
sellers_df.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [196]:
sellers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [197]:
sellers_df.shape

(3095, 4)

### Product Category name traslation

In [198]:
product_category_name_translation_df.head(5)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [199]:
product_category_name_translation_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [200]:
product_category_name_translation_df.shape

(71, 2)

## Data Quality Assessment

En esta etapa se evalúa la calidad de los datos para identificar posibles problemas que puedan afectar el análisis posterior.

Se revisarán aspectos como valores faltantes, registros duplicados y la consistencia de los tipos de datos con el fin de definir las transformaciones necesarias antes de construir el dataset analítico.

### Customer

In [201]:
customers_df.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [202]:
customers_df.duplicated().sum()

np.int64(0)

In [203]:
customers_df["customer_state"].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

### Geolocation

In [204]:
geolocation_df.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [205]:
geolocation_df.duplicated().sum()

np.int64(261831)

In [206]:
geolocation_df["geolocation_state"].value_counts()

geolocation_state
SP    404268
MG    126336
RJ    121169
RS     61851
PR     57859
SC     38328
BA     36045
GO     20139
ES     16748
PE     16432
DF     12986
MT     12031
CE     11674
PA     10853
MS     10431
MA      7853
PB      5538
RN      5041
PI      4549
AL      4183
TO      3576
SE      3563
RO      3478
AM      2432
AC      1301
AP       853
RR       646
Name: count, dtype: int64

In [207]:
geolocation_df["geolocation_city"].value_counts()

geolocation_city
sao paulo                     135800
rio de janeiro                 62151
belo horizonte                 27805
são paulo                      24918
curitiba                       16593
                               ...
são josé do herval                 1
almirante tamandaré do sul         1
são valentim                       1
três arroios                       1
ciríaco                            1
Name: count, Length: 8011, dtype: int64

### Order Items

In [208]:
order_items_df.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [209]:
order_items_df.duplicated().sum()

np.int64(0)

In [210]:
order_items_df[["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [211]:
order_items_df["order_item_id"].value_counts()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

### Order payments

In [212]:
order_payments_df.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [213]:
order_payments_df.duplicated().sum()

np.int64(0)

In [214]:
order_payments_df["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [215]:
order_payments_df[["payment_sequential", "payment_installments", "payment_value"]].describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

### Order Reviews

In [216]:
order_reviews_df.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       88285
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [217]:
(order_reviews_df.isnull().mean()*100).round(2)

review_id                   0.00
order_id                    0.00
review_score                0.00
review_comment_title       88.28
review_comment_message     58.25
review_creation_date        0.00
review_answer_timestamp     0.00
dtype: float64

In [218]:
order_reviews_df.duplicated().sum()

np.int64(0)

In [219]:
order_reviews_df["review_score"].value_counts()

review_score
5    57420
4    19200
1    11858
3     8287
2     3235
Name: count, dtype: int64

### fechas en string, Cambiar a Date

### Ordenes

In [220]:
orders_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [221]:
(orders_df.isnull().mean()*100).round(2)

order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
order_estimated_delivery_date    0.00
dtype: float64

### todas las en STR, pasar a date  , fijarse el porque de los null que hay dentro

In [222]:
orders_df.duplicated().sum()

np.int64(0)

In [223]:
orders_df["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

### Productos

In [224]:
products_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [225]:
(products_df.isnull().mean()*100).round(2)

product_id                    0.00
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

### ver las condiciones de los null y reemplazarlos por la media

In [226]:
products_df.duplicated().sum()

np.int64(0)

In [227]:
products_df["product_category_name"].value_counts()

product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 73, dtype: int64

In [228]:
products_df[["product_name_lenght", "product_description_lenght", "product_photos_qty", "product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"]].describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

### Sellers

In [229]:
sellers_df.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [230]:
sellers_df.duplicated().sum()

np.int64(0)

In [231]:
sellers_df["seller_city"].value_counts()

seller_city
sao paulo                 694
curitiba                  127
rio de janeiro             96
belo horizonte             68
ribeirao preto             52
                         ...
aparecida de goiania        1
bandeirantes                1
vitoria de santo antao      1
palotina                    1
leme                        1
Name: count, Length: 611, dtype: int64

In [232]:
sellers_df["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

### Product Category name traslation

In [233]:
product_category_name_translation_df.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [234]:
product_category_name_translation_df.duplicated().sum()

np.int64(0)

In [235]:
product_category_name_translation_df["product_category_name"].value_counts()

product_category_name
beleza_saude                     1
informatica_acessorios           1
automotivo                       1
cama_mesa_banho                  1
moveis_decoracao                 1
                                ..
flores                           1
artes_e_artesanato               1
fraldas_higiene                  1
fashion_roupa_infanto_juvenil    1
seguros_e_servicos               1
Name: count, Length: 71, dtype: int64

In [236]:
product_category_name_translation_df["product_category_name_english"].value_counts()

product_category_name_english
health_beauty                1
computers_accessories        1
auto                         1
bed_bath_table               1
furniture_decor              1
                            ..
flowers                      1
arts_and_craftmanship        1
diapers_and_hygiene          1
fashion_childrens_clothes    1
security_and_services        1
Name: count, Length: 71, dtype: int64

### Observaciones

El análisis de calidad permitió comprender el estado general de los datasets e identificar los principales aspectos que deberán considerarse durante la preparación de los datos.

En términos generales, la información presenta un buen nivel de calidad. La mayoría de las tablas no contienen valores faltantes ni registros duplicados, mientras que los problemas detectados se concentran principalmente en columnas específicas, como fechas almacenadas en formato texto y algunos valores nulos que responden al contexto propio del negocio.

Además, se observó que no todas las variables disponibles serán necesarias para el análisis. Por este motivo, la siguiente etapa estará enfocada en seleccionar únicamente la información relevante e integrar los distintos datasets para construir un conjunto de datos analítico orientado a la hipótesis del proyecto.

## Data Preparation

Luego de evaluar la estructura y la calidad de los datos, se definieron las variables que formarán parte del análisis en función de la hipótesis planteada.

Debido a que la información del marketplace Olist se encuentra distribuida en múltiples tablas relacionadas, será necesario integrarlas mediante sus claves de relación para construir un único dataset analítico. Este proceso permitirá reunir en una sola estructura la información de clientes, pedidos, productos, pagos y reseñas, facilitando el estudio de los factores que pueden influir en la satisfacción del cliente.

### Selección de variables

Durante la exploración inicial se identificó que algunos datasets incluyen atributos descriptivos que no aportan información relevante para responder la hipótesis del proyecto, como las dimensiones físicas de los productos, la cantidad de fotografías o la longitud de sus descripciones.

Por este motivo, se seleccionaron únicamente aquellas variables vinculadas al proceso de compra, la entrega del pedido, el valor de la transacción, la ubicación de clientes y vendedores, y la calificación otorgada por el cliente. Esta decisión permitirá construir un dataset más compacto, reducir información innecesaria y centrar el análisis en las variables con mayor impacto sobre el problema de negocio.

### Definición del dataset analítico

El modelo de datos de Olist distribuye la información de cada compra en diferentes tablas relacionadas entre sí. Las tablas **Orders** y **Order Items** constituyen el núcleo del modelo, ya que permiten vincular la información de clientes, productos, vendedores, pagos y reseñas mediante sus identificadores.

A partir de esta estructura relacional se definieron las variables que integrarán el dataset analítico, el cual servirá como base para las etapas de limpieza, creación de nuevas variables y análisis exploratorio orientado a validar la hipótesis del proyecto.

| Dataset            | Variables seleccionadas                                                                                                                                                                      | Justificación                                                                                                                                              |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Customers**      | `customer_id`, `customer_state`, `customer_city`                                                                                                                                             | Permiten identificar la ubicación del cliente y analizar si existen diferencias en la satisfacción según la región donde se realizó la compra.             |
| **Orders**         | `order_id`, `customer_id`, `order_status`, `order_purchase_timestamp`, `order_approved_at`, `order_delivered_carrier_date`, `order_delivered_customer_date`, `order_estimated_delivery_date` | Contiene la información principal del pedido y las fechas necesarias para calcular los tiempos de entrega y detectar posibles demoras.                     |
| **Order Items**    | `order_id`, `product_id`, `seller_id`, `price`, `freight_value`                                                                                                                              | Permite conocer el valor de los productos y del envío, variables que podrían influir en la percepción del cliente sobre la compra.                         |
| **Order Payments** | `order_id`, `payment_type`, `payment_installments`, `payment_value`                                                                                                                          | Incorpora información económica de cada pedido para evaluar si el monto abonado o la forma de pago presentan alguna relación con la calificación recibida. |
| **Order Reviews**  | `order_id`, `review_score`                                                                                                                                                                   | Contiene la calificación realizada por el cliente y constituye la variable principal sobre la que se desarrollará el análisis.                             |
| **Products**       | `product_id`, `product_category_name`                                                                                                                                                        | Permite analizar si determinadas categorías de productos presentan comportamientos diferentes respecto a la satisfacción del cliente.                      |
| **Sellers**        | `seller_id`, `seller_state`                                                                                                                                                                  | Incorpora la ubicación del vendedor, información que podrá utilizarse para estudiar diferencias regionales o ampliar el análisis en futuras etapas.        |

## Dataset Integration

Una vez definidas las variables que formarán parte del análisis, se procederá a integrar los diferentes datasets mediante sus claves de relación.

El objetivo es construir un único dataset analítico que concentre la información relevante de clientes, pedidos, productos, pagos y reseñas, manteniendo la integridad de los datos y preservando la mayor cantidad posible de registros.

In [237]:
analysis_df = orders_df.copy()

In [238]:
analysis_df = analysis_df.merge(customers_df[ ["customer_id","customer_state","customer_city"] ], on="customer_id", how="left")

In [239]:
analysis_df.shape

(99441, 10)

In [240]:
analysis_df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_state,customer_city
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,SP,sao paulo
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,BA,barreiras
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,GO,vianopolis
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,RN,sao goncalo do amarante
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,SP,santo andre

In [241]:
analysis_df = analysis_df.merge(order_reviews_df[["order_id", "review_score"]], on="order_id", how="left")

In [242]:
analysis_df.shape

(100000, 11)

In [243]:
analysis_df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_state,customer_city,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,SP,sao paulo,4
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,BA,barreiras,4
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,GO,vianopolis,5
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,RN,sao goncalo do amarante,5
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,SP,santo andre,5

### Analicis

Analizar la tabla ordenes ya que se encuentran mas filas lo que indica que indica una relacion 1 a muchos

In [247]:
orders_per_item = order_items_df["order_id"].value_counts().sort_values(ascending=False)

In [248]:
orders_per_item.head(5)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
Name: count, dtype: int64

In [271]:
cantidad = (orders_per_item > 1 ).sum()

total= orders_per_item.shape[0]

print(f"Total de órdenes: { (total)}")
print(f"Total de órdenes con múltiples items: { (cantidad)}")
print(f"Porcentaje: {(cantidad/total):.2%}")

Total de órdenes: 98666
Total de órdenes con múltiples items: 9803
Porcentaje: 9.94%

In [256]:
order_per_payments = order_payments_df["order_id"].value_counts().sort_values(ascending=False)

In [258]:
order_per_payments.head(5)

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
ee9ca989fc93ba09a6eddc250ce01742    19
Name: count, dtype: int64

In [273]:
cantidad = (order_per_payments > 1).sum()

total = order_per_payments.shape[0]

print(f"Total de órdenes: { (total)}")
print(f"Total de órdenes con múltiples payments: { (cantidad)}")
print(f"Porcentaje: {(cantidad/total):.2%}")

Total de órdenes: 99440
Total de órdenes con múltiples payments: 2961
Porcentaje: 2.98%

### Agregación de tablas con relaciones uno a muchos

Durante la exploración de los datos se identificó que las tablas **Order Items** y **Order Payments** presentan una relación de uno a muchos respecto a la tabla **Orders**. Esto significa que un mismo pedido puede contener varios productos o registrarse mediante múltiples transacciones de pago.

Para evitar la duplicación de registros durante la integración de los datos, ambas tablas serán agregadas a nivel de pedido. De esta forma, cada orden estará representada por una única fila, preservando la consistencia del dataset analítico y facilitando el análisis posterior.

In [275]:
order_items_summary = (order_items_df.groupby("order_id").agg( total_items=("order_item_id", "count"), total_price=("price", "sum"), total_freight=("freight_value", "sum"), unique_products=("product_id", "nunique"), unique_sellers=("seller_id", "nunique") ) .reset_index() )

order_items_summary.head(5)

,order_id,total_items,total_price,total_freight,unique_products,unique_sellers
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,1,1
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,1,1
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,1,1
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79,1,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,1,1

In [276]:
order_payments_summary = (order_payments_df.groupby("order_id").agg( payments_count=("payment_sequential", "count"), total_payment=("payment_value", "sum"), max_installments =("payment_installments", "max") ) .reset_index() )

order_payments_summary.head(5)

,order_id,payments_count,total_payment,max_installments
0,00010242fe8c5a6d1ba2dd792cb16214,1,72.19,2
1,00018f77f2f0320c557190d7a144bdd3,1,259.83,3
2,000229ec398224ef6ca0657da4fc703e,1,216.87,5
3,00024acbcdf0a6daa1e931b038114c75,1,25.78,2
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,218.04,3

In [277]:
analysis_df = analysis_df.merge( order_items_summary, on="order_id", how="left" )

In [278]:
analysis_df = analysis_df.merge( order_payments_summary, on="order_id", how="left" )

In [279]:
analysis_df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_state,customer_city,review_score,total_items,total_price,total_freight,unique_products,unique_sellers,payments_count,total_payment,max_installments
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,SP,sao paulo,4,1.0,29.99,8.72,1.0,1.0,3.0,38.71,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,BA,barreiras,4,1.0,118.70,22.76,1.0,1.0,1.0,141.46,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,GO,vianopolis,5,1.0,159.90,19.22,1.0,1.0,1.0,179.12,3.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,RN,sao goncalo do amarante,5,1.0,45.00,27.20,1.0,1.0,1.0,72.20,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,SP,santo andre,5,1.0,19.90,8.72,1.0,1.0,1.0,28.62,1.0

In [280]:
analysis_df.shape

(100000, 19)

In [281]:
analysis_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       100000 non-null  str
 1   customer_id                    100000 non-null  str
 2   order_status                   100000 non-null  str
 3   order_purchase_timestamp       100000 non-null  str
 4   order_approved_at              99839 non-null   str
 5   order_delivered_carrier_date   98207 non-null   str
 6   order_delivered_customer_date  97013 non-null   str
 7   order_estimated_delivery_date  100000 non-null  str
 8   customer_state                 100000 non-null  str
 9   customer_city                  100000 non-null  str
 10  review_score                   100000 non-null  int64
 11  total_items                    99222 non-null   float64
 12  total_price                    99222 non-null   float64
 13  total_freight                  99222 non-null   float64
 14  unique_products                99222 non-null   float64
 15  unique_sellers                 99222 non-null   float64
 16  payments_count                 99999 non-null   float64
 17  total_payment                  99999 non-null   float64
 18  max_installments               99999 non-null   float64
dtypes: float64(8), int64(1), str(10)
memory usage: 14.5 MB

In [283]:
analysis_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 161
order_delivered_carrier_date     1793
order_delivered_customer_date    2987
order_estimated_delivery_date       0
customer_state                      0
customer_city                       0
review_score                        0
total_items                       778
total_price                       778
total_freight                     778
unique_products                   778
unique_sellers                    778
payments_count                      1
total_payment                       1
max_installments                    1
dtype: int64

In [282]:
analysis_df.duplicated().sum()

np.int64(350)

In [ ]:
analysis_df.loc[ analysis_df["total_items"].isna(), ["order_id", "order_status"] ].head(20)

                              order_id order_status
266   8e24261a7e58791d10cb1bf9da94df5c  unavailable
588   c272bcd21c287498b4883c7512019702  unavailable
691   37553832a3a89c9b2db59701c357ca67  unavailable
741   d57e15fb07fd180f06ab3926b39edcd2  unavailable
1136  00b1cb0320190ca0daa2c88b35206009     canceled
1167  2f634e2cebf8c0283e7ef0989f77d217  unavailable
1587  ee0db22a8e742b752914016708470ec8  unavailable
1811  ed3efbd3a87bea76c2812c66a0b32219     canceled
1836  6ad57aecbae806a7e9cc2cdb6b380711  unavailable
1878  df8282afe61008dc26c6c31011474d02     canceled
2040  8d4c637f1accf7a88a4555f02741e606     canceled
2161  9f3458f0433d4cfa472f4682654b8d49  unavailable
2174  7a9d4c7f9b068337875b95465330f2fc     canceled
2310  f0df036e9be21fc238f131bbfcdde769  unavailable
2330  86f0bcd9b426a2c1022ae317c7f27be6  unavailable
2695  98fe01bc254b759c1f2c11d77c2891d5  unavailable
2722  f56dc9034c3962e36d49fb73baa12800  unavailable
2987  0130f0f71fb0e831d18e6a3b33a3a50c  unavailable
3072  ddaec6fff982b13e7e048b627a11d6da     canceled
3100  84b8ba39037606b7b30a39d02e9e4154  unavailable

In [285]:
analysis_df[analysis_df.duplicated()].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_state,customer_city,review_score,total_items,total_price,total_freight,unique_products,unique_sellers,payments_count,total_payment,max_installments
406,ac7a92560a9e99f0a0ab4988102f491b,6abf781c5304890987047e9aa239caa8,delivered,2018-03-04 15:58:09,2018-03-04 16:10:35,2018-03-06 17:14:59,2018-03-22 23:44:33,2018-03-23 00:00:00,PR,londrina,1,1.0,89.99,17.88,1.0,1.0,1.0,107.87,6.0
557,7845a2492ab1b4f2cf3d56c7b8da1446,386e96046ce0e77e5c9a9a4e818da93c,delivered,2018-01-18 12:35:45,2018-01-18 12:56:40,2018-01-18 23:42:44,2018-01-23 21:51:48,2018-02-09 00:00:00,PR,curitiba,5,1.0,29.99,14.10,1.0,1.0,1.0,44.09,1.0
616,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,canceled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaN,2018-02-22 00:00:00,SP,diadema,1,1.0,69.90,26.11,1.0,1.0,1.0,96.01,4.0
672,acbe07f22f29ad7e5a78f30008cc6ec7,b4afeb58ac51bc903c5362286c6a5cfe,delivered,2017-11-18 14:33:04,2017-11-18 19:06:16,2017-11-27 18:34:31,2017-11-29 17:58:43,2017-12-05 00:00:00,SP,sao paulo,5,4.0,77.20,46.92,4.0,1.0,1.0,124.12,2.0
1095,5e4c365dd3cf7769a88981f408d069d3,15f7712bb12fe27068e5353d14503653,delivered,2017-11-21 21:31:09,2017-11-23 02:47:29,2017-11-28 23:33:04,2017-12-23 16:13:34,2017-12-12 00:00:00,RJ,rio de janeiro,1,1.0,89.99,17.88,1.0,1.0,1.0,107.87,1.0

In [286]:
analysis_df["order_id"].duplicated().sum()

np.int64(559)

In [288]:
order_reviews_df["order_id"].duplicated().sum()

np.int64(559)